[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'


[languages]
  [languages.en]
    disabled = false
    languageName = 'English'
    languageCode = 'en-gb'
    weight = 1
    default = true
    [[languages.en.menu.main]]
      name = "Home"
      URL = "#home"
      weight = 1
    [[languages.en.menu.main]]
      name = "Experiences"
      URL = "#experience"
      weight = 2
    [[languages.en.menu.main]]
      name = "Education"
      URL = "#educations"
      weight = 3
    [[languages.en.menu.main]]
      name = "Publications"
      URL = "#publications"
      weight = 4
    [[languages.en.menu.main]]
      name = "Portfolio"
      URL = "#portfolio"
      weight = 5
    [[languages.en.menu.main]]
      name = "Contact"
      URL = "#contact"
      weight = 6

  [languages.fr]
      disabled = false
      languageName = 'French'
      languageCode = 'fr-FR'
      weight = 2
      [[languages.fr.menu.main]]
        name = "Accueil"
        URL = "#home"
        weight = 1
      [[languages.fr.menu.main]]
        name = "Expériences"
        URL = "#experience"
        weight = 2
      [[languages.fr.menu.main]]
        name = "Formations"
        URL = "#educations"
        weight = 3
      [[languages.fr.menu.main]]
        name = "Publications"
        URL = "#publications"
        weight = 4
      [[languages.fr.menu.main]]
        name = "Portfolio"
        URL = "#portfolio"
        weight = 5
      [[languages.fr.menu.main]]
        name = "Contact"
        URL = "#contact"
        weight = 6

  [languages.mg]
    disabled = false
    languageName = 'Malagasy'
    languageCode = 'mg-mg'
    weight = 3
    [[languages.mg.menu.main]]
      name = "Fandraisana"
      URL = "#home"
      weight = 1
    [[languages.mg.menu.main]]
      name = "Traikefa"
      URL = "#experience"
      weight = 2
    [[languages.mg.menu.main]]
      name = "Fianarana"
      URL = "#educations"
      weight = 3
    [[languages.mg.menu.main]]
      name = "Asa soratra"
      URL = "#publications"
      weight = 4
    [[languages.mg.menu.main]]
      name = "Portfolio"
      URL = "#portfolio"
      weight = 5
    [[languages.mg.menu.main]]
      name = "Fifandraisana"
      URL = "#contact"
      weight = 6

############################# Site Map ##############################
# See the sitemap block later for final values

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"

# JS Plugins

############################## navigation ###############################

# main menu

#################### default parameters ################################
[params]
    logo_light = "images/favicon_io/android-chrome-192x192.png"
    logo_dark = "images/favicon_io/android-chrome-192x192.png"
    copyright = "Jean Lucien Randrianantenaina ©"

    # Meta data
	baseURL = 'https://fahazavana.github.io/'
	title = 'Jean Lucien Randrianantenaina'
	screenshot="images/og_image.png"
    description = "Personal Portfolio"
    author = "Jean Lucien Randrianantenaina"
    favicon = "images/favicon_io/android-chrome-192x192.png"
    google_analytics = "GTM-WFHLNFTN"
    twitter = "rjlucienaina"

[params.sitemap]
  changefreq = "weekly"
  priority = 0.5

# google-site-ver
[params.googleSiteVerification]
  name = "google-site-verification"
  content = "aUm25JeP5P0ARrayqp0nUugz1QnRRJ-GGQeCbpb26_Q"

# Preloader
[params.preloader]
    enable = true
    preloader = "images/preloader.gif"


############################# Localisation ########################
[params.location]
    icon = "fa-solid fa-location-dot"
    place = "Fianarantsoa, Madagascar"

# Final sitemap configuration
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "Sitemap"]

############################# social site ########################

[[params.social]]
icon = "fab fa-github"
class = "text-muted hover:text-primary"
link = "https://github.com/Fahazavana"

[[params.social]]
icon = "fab fa-linkedin"
class = "text-muted hover:text-primary"
link = "https://linkedin.com/in/jean-lucien-randrianantenaina-82b98622b"

[[params.social]]
icon = "fab fa-x-twitter"
link="https://twitter.com/rjlucienaina"
class = "text-muted hover:text-primary"

[[params.social]]
icon = "fa fa-envelope"
class = "text-muted hover:text-primary"
link = "mailto:rjlucienaina@gmail.com"

[[params.social]]
icon = "fa-brands fa-whatsapp"
class = "text-muted hover:text-primary"
link = "https://wa.me/261345898164"
